# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Check User Permission'
description: 'A GitHub Action to check user permission of the current repository.'
author: 'xrkffgg'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'user-x'
  color: 'purple'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  require:
    description: Which permission level a user should have
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
